### ISSUE TITLE
parsing issue

### ISSUE THREAD

**Issue by sajjadahmed677** [ovh/sv2chisel#1]
hello every one i am having following error while compiling my file will you please guide why it is happening.

[error] (run-main-9) sv2chisel.SV2ChiselInternalException: Internal Error! Parser Issue () in context: bit
[error] Please file an issue at ...
[error] sv2chisel.SV2ChiselInternalException: Internal Error! Parser Issue () in context: bit
[error] Please file an issue at ...
[error]         at sv2chisel.Utils$.error(Utils.scala:151)
[error] oot / Coat sv2chisel.Utils$.throwInternalError(Utils.scala:139)
[error] 	at sv2chisel.Visitor.throwParserError(Visitor.scala:43)
[error] 	at sv2chisel.Visitor.getIntegerType(Visitor.scala:234)
[error] 	at sv2chisel.Visitor.getDataPrimitiveType(Visitor.scala:249)
[error] 	at sv2chisel.Visitor.getDataTypeUsual(Visitor.scala:291)
[error] 	at sv2chisel.Visitor.getDataType(Visitor.scala:324)
[error] 	at sv2chisel.Visitor.visitData_type_or_implicit(Visitor.scala:1118)
[error] 	at sv2chisel.Visitor.visitParamDeclPrim(Visitor.scala:1274)
[error] 	at sv2chisel.Visitor.visitParameter_declaration(Visitor.scala:1283)
[error] 	at sv2chisel.Visitor.visitParameterDeclaration(Visitor.scala:1300)
[error] 	at sv2chisel.Visitor.$anonfun$visitParams$2(Visitor.scala:1317)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[error] 	at sv2chisel.Visitor.visitParams(Visitor.scala:1317)
[error] 	at sv2chisel.Visitor.visitModule(Visitor.scala:2140)
[error] 	at sv2chisel.Visitor.visitDescription(Visitor.scala:57)
[error] 	at sv2chisel.Visitor.$anonfun$visitSourceText$1(Visitor.scala:47)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sv2chisel.Visitor.visitSourceText(Visitor.scala:47)
[error] 	at sv2chisel.Visitor.visit(Visitor.scala:29)
[error] 	at sv2chisel.Parser$.$anonfun$parseCharStream$3(Parser.scala:55)
[error] 	at sv2chisel.Utils$.time(Utils.scala:144)
[error] 	at sv2chisel.Parser$.parseCharStream(Parser.scala:55)
[error] 	at sv2chisel.Parser$.parseFile(Parser.scala:28)
[error] 	at sv2chisel.Project.$anonfun$addFiles$1(Project.scala:36)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at sv2chisel.Project.addFiles(Project.scala:35)
[error] 	at sv2chisel.Project$.apply(Project.scala:177)
[error] 	at MyTranslator$.delayedEndpoint$MyTranslator$1(MyTranslator.scala:24)
[error] 	at MyTranslator$delayedInit$body.apply(MyTranslator.scala:4)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.App.main(App.scala:80)
[error] 	at scala.App.main$(App.scala:78)
[error] 	at MyTranslator$.main(MyTranslator.scala:4)
[error] 	at MyTranslator.main(MyTranslator.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] stack trace is suppressed; run last Compile / bgRunMain for the full output
[error] Nonzero exit code: 1
[error] (Compile / runMain) Nonzero exit code: 1

**Comment by Reset12138** [comment]
encounter same error too, no matter on windows or linux
have you solve it?

**Comment by johnsbrew** [comment]
Closing this with release 0.5.0
@Reset12138 & @sajjadahmed677 do not hesitate to try again with the newest version, largely improved since then!
