### ISSUE TITLE
Error: Could not find or load main class sv2chisel.Main

### ISSUE THREAD

**Issue by Martoni** [ovh/sv2chisel#7]
I can't execute binary utility correctly.

I published localy the project : 

```shell
$ git clone https://github.com/ovh/sv2chisel.git
$ cd sv2chisel
$ sbt
sbt:sv2chisel> publishLocal
sbt:sv2chisel> helpers/publishLocal
```
I found the binary under directory named utils/bin : 

```shell
$ cd utils/bin/
$ ./sv2chisel -help
Error: Could not find or load main class sv2chisel.Main
Caused by: java.lang.ClassNotFoundException: sv2chisel.Main
```
Did I forget something in installation ?

**Comment by johnsbrew** [comment]
Hi @Martoni 

There are many different ways to get sv2chisel working.
The easiest is to download standalone binaries from releases : https://github.com/ovh/sv2chisel/releases/tag/v0.5.0

As you've already cloned the repositories, the second easiest consists in assembling the code base into a fat jar with `sbt assembly` (or simply `assembly` within sbt) command. Then `./utils/bin/sv2chisel` should work as expected.

Another option is to play within the sbt command prompt with `runMain sv2chisel.Main -help` command as proposed here: https://github.com/ovh/sv2chisel#option-a-run-the-generic-application

In all cases this might be useful : https://github.com/ovh/sv2chisel#1-translation

Further details about translation options (default are usually fine): https://github.com/ovh/sv2chisel/blob/master/FEATURES_LIMITATIONS.md#configuration--translation-options  

I hope this helps, let me know if you need anything :)

**Comment by Martoni** [comment]
Works \o/
Thanks
